---
title: 'Hidden Confounder'
output: html_document
date: "2024-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# Libraries
library(data.table)
library(survival)
#install.packages("rtmle")
#devtools::install_github("tagteam/rtmle")
library(rtmle)
library(ggplot2)
library(microbenchmark)
theme_set(theme_bw())
source("~/Helene_projekt/funcs_for_two_settings.R")
```


# Interventions

```{r}
# 1. Use simulation function to generate one dataset of reasonable size n.
data0 <- sim_data_setting1(N = 5000, cens = 0)

# 2. On that data, estimate a marginal intensity/hazard of operation; perhaps use a Weibull regression?
data0[, at_risk_oper := as.numeric(A == 0)]
survfit <- survreg(Surv(Time, Delta == 0) ~ L0 + L, 
                   data = data0[at_risk_oper == 1], 
                   cluster = ID,
                   dist='weibull')

# 3. Use your simulation function to make a large data set under the intervened intensity 
nu_est <- 1/survfit$scale; nu_est
eta_est <- 1/exp(survfit$coefficients[1]); eta_est
beta_l0_a_est <- - survfit$coefficients[2] / survfit$scale 
beta_l_a_est <- - survfit$coefficients[3] / survfit$scale 

# 4. Compute the average of subjects dying before some time tau. Do the same in the setting where all operation events are removed. 

data_under_int <- sim_data_setting1(N = 5000, cens = 0,
                                    eta = c(rep(0.1,3), eta_est),
                                    nu = c(rep(1.1,3), nu_est),
                                    beta_L0_A = beta_l0_a_est,
                                    beta_L_A = beta_l_a_est)


data_under_int_no_op <- sim_data_setting1(N = 5000, cens = 0, 
                                          op = 0, eta = c(rep(0.1,3), eta_est),
                                          nu = c(rep(1.1,3), nu_est),
                                          beta_L0_A = beta_l0_a_est,
                                          beta_L_A = beta_l_a_est)

#average of subjects dying before some time tau
tau <- 5
mean(data_under_int[Delta == 1, Time] < tau) # With operations
mean(data_under_int_no_op[Delta == 1, Time] < tau) # No operation


# We might have problems with time varying covariates - evt prøv det her
#flexsurv::flexsurvreg(formula = Surv(tstart, tstop, Delta == 0) ~ L0 + L, 
#                      data=set1_data_t,
#                      dist = "weibull") 

#set1_data_t <- trans_int_data(data0)

#set1_data_t[, at_risk_oper := as.numeric(A == 0)]
#set1_data_t[, at_risk_cov := as.numeric(L == 0)]

#survfit_oper <- coxph(Surv(tstart, tstop, Delta == 0) ~ L0 + L, 
#                      data = set1_data_t[at_risk_oper == 1], cluster = ID)
```


