---
title: 'Simulation Study: Two Settings'
output: html_document
date: "2024-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Libraries
library(data.table)
library(survival)
#install.packages("rtmle")
#devtools::install_github("tagteam/rtmle")
library(rtmle)
library(ggplot2)
library(microbenchmark)
theme_set(theme_bw())
```


To do:
- proportion af censoreringer, død, osv.
- followup period

# Two Settings

## Setting 1 ("Operation")

```{r}
set.seed(2964)
set1_data <- sim_data_setting1(N = 10000)
set1_data_fu <- sim_data_setting1(N = 10000, followup = 5)
plot_event_data(set1_data)
plot_event_data(set1_data_fu)
```

## Setting 2 ("T2D diabetes")

```{r}
set.seed(2964)
set2a_data <- sim_data_setting2(N = 10000, setting = "a")
set2b_data <- sim_data_setting2(N = 10000, setting = "b")
set2a_fu_data <- sim_data_setting2(N = 10000, setting = "a", followup = 5)
set2b_fu_data <- sim_data_setting2(N = 10000, setting = "b", followup = 5)
```


```{r}
plot_event_data(set2a_data)
plot_event_data(set2a_fu_data)
```


### Proportions

```{r}
summary_sim_event <- function(data) {
  N <- nrow(data)
  prop_op <- nrow(data[Delta == 0])/N
  prop_death <- nrow(data[Delta == 1])/N
  prop_cens <- nrow(data[Delta == 2])/N
  prop_fu_cens <- nrow(data[Delta == "C"])/N
  prop_cov <-  nrow(data[Delta == 3])/N
  
  mean_T <- mean(data$Time)
  max_T <- max(data$Time)
  
  return(data.table("Prop Op" = prop_op, "Prop Death" = prop_death, "Prop Cens" = prop_cens, 
                    "Prop FU Cens" = prop_fu_cens, "Prop Cov" = prop_cov, "Mean Time" = mean_T, 
                    "Max Time" = max_T))
}
```

```{r}
summary_sim_event(set1_data)
summary_sim_event(set1_data_fu)
summary_sim_event(set2a_data)
summary_sim_event(set2a_fu_data)
summary_sim_event(set2b_data)
summary_sim_event(set2b_fu_data)
```

### Investigating modl misspecifications

```{r}
# Transform data into tstart tstop format
set1_data_int <- trans_int_data(set1_data)

set1_data_int[, at_risk_oper := as.numeric(A == 0)]
set1_data_int[, at_risk_cov := as.numeric(L == 0)]

# True models:
survfit_oper <- coxph(Surv(tstart, tstop, Delta == 0) ~ L0 + L, 
                      data = set1_data_int[at_risk_oper == 1], cluster = ID)
survfit_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A + L, 
                       data = set1_data_int, cluster = ID)
survfit_cens <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A + L, 
                      data = set1_data_int, cluster = ID)
survfit_cov <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A, 
                     data = set1_data_int[at_risk_cov == 1], cluster = ID)

# Cox models only with time varying covariate:

survfit_oper1 <- coxph(Surv(tstart, tstop, Delta == 0) ~ L0 + L, 
                      data = set1_data_int[at_risk_oper == 1], cluster = ID)
survfit_death1 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + L, 
                       data = set1_data_int, cluster = ID)
survfit_cens1 <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + L, 
                      data = set1_data_int, cluster = ID)
survfit_cov1 <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0, 
                     data = set1_data_int[at_risk_cov == 1], cluster = ID)

# Cox models only with operation:
survfit_oper2 <- coxph(Surv(tstart, tstop, Delta == 0) ~ L0, 
                      data = set1_data_int[at_risk_oper == 1], cluster = ID)
survfit_death2 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A, 
                       data = set1_data_int, cluster = ID)
survfit_cens2 <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A, 
                      data = set1_data_int, cluster = ID)
survfit_cov2 <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A, 
                     data = set1_data_int[at_risk_cov == 1], cluster = ID)


survfit_oper$coefficients; survfit_oper1$coefficients; survfit_oper2$coefficients
survfit_death$coefficients; survfit_death1$coefficients; survfit_death2$coefficients
survfit_cens$coefficients; survfit_cens1$coefficients; survfit_cens2$coefficients
survfit_cov$coefficients; survfit_cov1$coefficients; survfit_cov2$coefficients

```

### Fitting models

```{r}
# Transform data into tstart tstop format
set2a_data_int <- trans_int_data(set2a_data)

set2a_data_int[, at_risk_cov := as.numeric(L == 0)]

# Fit models
survfit_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0  + A0 + L, 
                       data = set2a_data_int, cluster = ID)
survfit_cens <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0 + L, 
                      data = set2a_data_int, cluster = ID)
survfit_cov <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A0, 
                     data = set2a_data_int[at_risk_cov == 1], cluster = ID)

survfit_death$coefficients 
survfit_cens$coefficients 
survfit_cov$coefficients
```

```{r}
# Transform data into tstart tstop format
set2b_data_int <- trans_int_data(set2b_data)

set2b_data_int[, at_risk_cov := as.numeric(L == 0)]

# Fit models
survfit_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0  + A0 + L, 
                       data = set2b_data_int, cluster = ID)
survfit_cens <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0 + L, 
                      data = set2b_data_int, cluster = ID)
survfit_cov <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A0, 
                     data = set2b_data_int[at_risk_cov == 1], cluster = ID)

survfit_death$coefficients 
survfit_cens$coefficients 
survfit_cov$coefficients
```


### Proportions


Note that we can affect the intensities by:

$$\lambda^x_k(t\, \vert \, \mathcal{F}_{t-}) =  R^x(t,k)  \eta^x \nu^x t^{\nu^x - 1} 
 \exp(\beta^T Z)$$

changing the value of $\eta^x$. For a follow up time $K$ 

```{r}
eta_vals <- rep(0.05, 4)
incr <- 0.05
K <- 5
summaries <- list()

for(i in 1:12){
  sim <- sim_data_setting2(1000, eta = eta_vals, followup = K)
  summaries[[i]] <- summary_sim_event(sim)
  eta_vals[i %% 4] <- eta_vals[i %% 4] + incr
}


```






























