---
title: 'Simulation study: Cause Specific Hazards'
output: html_document
date: "2024-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Libraries
library(gridExtra)
library(tidyverse)
```


# Competing risk

Simulation of covariates to time 0:

```{r}
n <- 1700

X0 <- rbinom(n, 1, 0.1627)
X1 <- rpois(n, 35)
L0 <- cbind(X0, X1)

# Effekt
alpha <- c(0, 0)
beta <- c(0.5816, -0.1)
```

Hazard functions

```{r}
# Parameters
lambda <- 0.0271
v <- 1.3841

# Specify hazard functions
weib_haz <- function(t) lambda * v * t ^ (v - 1)
weib_cum_haz <- function(t) lambda * t ^ v 

# Cause specific hazard functions
haz1 <- function(t) weib_haz(t) * exp(L0 %*% alpha)
haz2 <- function(t) weib_haz(t) * exp(L0 %*% beta)
```

Distribution function and inverse distribution function

```{r}
# CDF of time to any event T
F_func <- function(t, x) {
  1 - exp( - (weib_cum_haz(t) * exp(t(alpha) %*% x) + 
            weib_cum_haz(t) * exp(t(beta) %*% x)))
}

# Inverse of the distribution function

inverse_F <- function(p, x, lower_bound = 0, upper_bound = 100) {
  # Define the root-finding function (F(t) - p)
  root_function <- function(t) {
    F_func(t, x) - p
  }
  # Use uniroot to find the value of t such that F(t) = y
  result <- uniroot(root_function, lower = lower_bound, upper = upper_bound)
  
  # Return the value of t
  return(result$root)
}
```

Simulating time to event variables

```{r}
# Simulating uniform random variables
Z <- runif(n)
# Simulating event times
Ts <-  numeric(n)
for(i in 1:n){
  Ts[i] <- inverse_F(p = Z[i], x = L0[i,])
}

# Simulating censoring
censoring_time <- rweibull(n, 1.3841, 1/0.0271)
# The event variable
event <- ifelse(Ts <= censoring_time, 1, 0)
```

Simulating the cause

```{r}
# The probability of cause of event being 1
p1 <- haz1(Ts) / (haz1(Ts) + haz2(Ts))

cause_type <- ifelse(event == 1, rbinom(n, 1, 1 - p1) + 1, 0) # 1 indicates cause 1, 2 indicates cause of event being 2

# Cause specific event times
T1 <- Ts[cause_type == 1]
T2 <- Ts[cause_type == 2]
```

Plots of distribution of evnt times

```{r}
plot_1 <- ggplot(data = data.frame(T1 = T1), aes(x = T1, y = ..density..)) + 
  geom_histogram(binwidth = 1, fill = "blue", alpha = 0.5) + 
  theme_minimal()+
  labs(title = "Cause 1")

plot_2 <- ggplot(data = data.frame(T2 = T2), aes(x = T2, y = ..density..)) + 
  geom_histogram(binwidth = 1, fill = "blue", alpha = 0.5) + 
  theme_minimal()+
  labs(title = "Cause 2")

grid.arrange(plot_1, plot_2, ncol = 2)
```

Output of function

```{r}
tibble(
  Id = n,
  X0 = X0,
  X1 = X1,
  "Time to event" = Ts,
  "Cause" = cause_type
)
```




