---
title: 'T2D'
output: html_document
date: "2024-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, include=FALSE}
# Libraries
library(data.table)
library(survival)
#install.packages("rtmle")
#devtools::install_github("tagteam/rtmle")
library(rtmle)
library(ggplot2)
library(microbenchmark)
theme_set(theme_bw())
source("~/Helene_projekt/funcs_for_two_settings.R")
```


```{r}
#plot_event_data(set2a_data)
#summary_sim_event(set2a_data)
# Fitting models
# Transform data into tstart tstop format
#mod_data_a <- trans_int_data(set2a_fu_data)
#mod_data_a[, at_risk_cov := as.numeric(L == 0)]
## Fit models
#survfit_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0  + A0 + L, 
#                       data = mod_data_a, cluster = ID)
#survfit_cens <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0 + L, 
#                      data = mod_data_a, cluster = ID)
#survfit_cov <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A0, 
#                     data = mod_data_a[at_risk_cov == 1], cluster = ID)
#survfit_death$coefficients 
#survfit_cens$coefficients 
#survfit_cov$coefficients
```

# A more meaningful estimand

## Thomas Gerds forslag


```{r}
N <- 1000
data_A <- sim_data_setting2(N = N, beta_L_D = 1, cens = 1)

# Finding all the T2D people and setting T_0 to debut time of diabetes
T2D_events <- data_A[Delta == 3]
T2D_peeps <- data_A[ID %in% T2D_events$ID]
T2D_peeps[, Time_T2D := Time - min(Time), by = ID]
T2D_peeps <- T2D_peeps[Delta != 3]
T2D_peeps[, Status := Delta == 1]

data_A[Delta == 3, Time] |> summary()

# Kaplan Meyer fit
library(prodlim)
fit <- prodlim(Hist(Time_T2D, Status) ~ L0 + A0, data = T2D_peeps)
#plot(fit)

plot(fit, newdata = data.frame(L0 = c(0.5,0.5), A0 = c(0,1)))
```



```{r}
diff_betas <- seq(0,1,by = 0.1)
N <- 500
B <- length(diff_betas)

ests <- matrix(nrow = B, ncol = 2*3)

for(b in 1:B){
  print(b)
  data0 <- sim_data_setting2(N = N, beta_L_D = diff_betas[b], beta_A0_L = 0)
  data0.5 <- sim_data_setting2(N = N, beta_L_D = diff_betas[b], beta_A0_L = 0.5)
  data1 <- sim_data_setting2(N = N, beta_L_D = diff_betas[b], beta_A0_L = 1)
  
  index <- 0
  for(data in list(data0,data0.5, data1)){
    # Finding all the T2D people and setting T_0 to debut time of diabetes
    T2D_events <- data[Delta == 3]
    T2D_peeps <- data[ID %in% T2D_events$ID]
    T2D_peeps[, Time_T2D := Time - min(Time), by = ID]
    T2D_peeps <- T2D_peeps[Delta != 3]
    T2D_peeps[, Status := Delta == 1]
    
    # Kaplan meyer fit
    fit <- prodlim(Hist(Time_T2D, Status) ~ L0 + A0, data = T2D_peeps)
    
    # Save estimate
    preds <- predict(fit, times = 5, newdata = data.frame(L0 = c(0.5,0.5), A0 = c(0,1)))
    ests[b,(index + 1)] <- preds$`L0=0.5, A0=0`
    ests[b,(index + 2)] <- preds$`L0=0.5, A0=1`
    index <- index + 2
  }
}
```


```{r}
data.table("No effect of drug on T2D" = ests[,2] - ests[,1], 
           "Effect of drug on T2D" = ests[,4] - ests[,3], 
           "Large effect of drug on T2D" = ests[,6] - ests[,5],
           beta = rep(diff_betas,2))


plot_data <- data.table(Est = c(ests), Treat = as.factor(c(rep(0,B), rep(1,B))),
                        

ggplot(plot_data)+
  geom_line(aes(x = beta, y = Est, group = Treat, col = Treat))+
  ylab("Estimated survival probability at Time = 5")+
  labs("5 year survival probability since T2D")
```

Skal vi i virkeligheden variere hvordan A0 påvirker sandsynligheden for overlevelse?
Kan vi finde den sande værdi?

## Helene forslag

```{r}
# Generate large data
N <- 50000
data_A <- sim_data_setting2(N = N, beta_L_D = 1, cens = 0)
data_A[, at_risk_cov := as.numeric(L == 0)]


# Grouping data based on treatment
no_treat_group <- data_A[A0 == 0]
treat_group <- data_A[A0 == 1]


# Fit Weibull, hvordan fitter jeg den her?
survfit <- survreg(Surv(Time, Delta == 3) ~ L0, 
                   data = no_treat_group[at_risk_cov == 1], 
                   cluster = ID,
                   dist='weibull')

survfit1 <- survreg(Surv(Time, Delta == 3) ~ L0, 
                   data = treat_group[at_risk_cov == 1], 
                   cluster = ID,
                   dist='weibull')

# Tjek af estimater
nu_est <- 1/survfit$scale; nu_est
eta_est <- 1/exp(survfit$coefficients[1]); eta_est
beta_l0_l_est <- - survfit$coefficients[2] / survfit$scale; beta_l0_l_est

# Hvorfor får vi ikke en anden intensitet???

1/survfit1$scale
1/exp(survfit1$coefficients[1])
- survfit1$coefficients[2] / survfit1$scale

# Generate large data set under the intervened intensity 
N <- 10000
data_new <- sim_data_setting2(N = N, 
                              cens = 0,
                              eta = c(rep(0.1,3), eta_est),
                              nu = c(rep(1.1,3), nu_est),
                              beta_L0_L = beta_l0_l_est)

# Generate large data set without intervened intensity 
data_new_no_int <- sim_data_setting2(N = N, cens = 0)

#average of subjects dying before some time tau
tau <- 5
mean(data_new[Delta == 1, Time] < tau) # with intervention
mean(data_new_no_int[Delta == 1, Time] < tau) # without intervention
```


