---
title: "Interventions Confounder"
author: "Michaela Lukacova"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# Libraries
library(data.table)
library(survival)
library(simevent)
library(ggplot2)
library(microbenchmark)
theme_set(theme_bw())
```


# Monte Carlo Approximation of True Value

```{r}
set.seed(103)
B1 <- 10
N1 <- 6*10^5
N2 <- 6*10^5
tau <- 2
MC_ests <- matrix(nrow = B1, ncol = 2)

for(i in 1:B1){
  print(i)
  
  # Generate data without intervention
  data1 <- simConfounding(N = N2, beta_L_A = 3, beta_L_D = 3, beta_A_D = -0.5, 
                          beta_A_L = -0.5, beta_L0_A = 1, beta_L0_L = 1, 
                          beta_L0_D = 1, cens = 0, op = 1)
  
  # Generate data under intervention
  dataInt <- simConfounding(N = N2, beta_L_A = 0, beta_L_D = 3, beta_A_D = -0.5, 
                            beta_A_L = -0.5, beta_L0_A = 0, beta_L0_L = 1, beta_L0_D = 1, 
                            cens = 0, op = 0)
  
  MC_ests[i,] <- c(mean(data1[Delta == 1, Time] < tau), # Data under observed probability distribution
                   mean(dataInt[Delta == 1, Time] < tau)) # Intervened data
}
```

```{r}
beta_true <- mean(MC_ests[,1]- MC_ests[,2])
sd_beta_true <- sd(MC_ests[,1]- MC_ests[,2])

beta_true
sd_beta_true
```

# Estimation

Gentagne estimationer:

```{r}
B <- 400
tau <- 2
N1 <- 1000
N2 <- 10^5

# For results
simres_conf <- matrix(nrow = B, ncol = 2)

for(b in 1:B){
  print(b)
  # Generate "observed" data
  data <- simConfounding(N = N1, beta_L_A = 3, beta_L_D = 3, beta_A_D = -0.5,
                          beta_A_L = -0.5, beta_L0_A = 1, beta_L0_L = 1,
                          beta_L0_D = 1, cens = 1, op = 1)
    
  data_int <- IntFormatData(data, N_cols = 5:6)

  # Fit Cox models
  cox_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A + L, data = data_int)
  cox_treat <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + L, data = data_int[A == 0])
  cox_conf <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A, data = data_int[L == 0])
  cox_fits <- list("D" = cox_death, "A" = cox_treat, "L" = cox_conf)
  
  # Simulate under "observed" intensities
  data0 <- simEventCox(N2,
                       cox_fits, 
                        L0_old = data$L0, 
                        A0_old = 0,
                        n_event_max = c(1,1,1))
  
  # Simulate under intervention
  data_int <- simEventCox(N2, 
                          cox_fits, 
                          L0_old = data$L0, 
                          A0_old = 0, 
                          n_event_max = c(1,0,1))
  
  # Calculate estimate and save
  simres_conf[b,] <- c(mean(data0[Delta == 1, Time] < tau),
                  mean(data_int[Delta == 1, Time] < tau))
}
```

```{r}
mean(simres_conf[,1]-simres_conf[,2])
sd(simres_conf[,1]-simres_conf[,2])
quantile((simres_conf[,1]-simres_conf[,2]), 0.025)
quantile((simres_conf[,1]-simres_conf[,2]), 0.975)

pp<- ggplot()+
  geom_histogram(aes(x = simres_conf[,1]-simres_conf[,2], y = ..density..), color = "white", fill = "steelblue",
                 bins = 30)+
  geom_vline(xintercept = -0.0333, color = "darkred")+
  xlab("Estimate") 

ggsave("hist_sim_int_conf.jpeg", pp, width = 7, height = 5)
```


