---
title: "T2D"
output:
  pdf_document: default
  html_document: default
date: "2024-10-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, include=FALSE}
# Libraries
library(data.table)
library(survival)
library(simevent)
library(ggplot2)
library(prodlim)
library(rstpm2)
theme_set(theme_bw())
```

# Monte Carlo approximation

```{r}
B1 <- 10
N1 <- 2 * 10^5
N2 <- 2 * 10^5
tau <- 2

set.seed(927)
MC_ests_T2D <- matrix(nrow = B1, ncol = 2)
for(b in 1:B1){
  print(b)
  # Simulate
  data <- simT2D(N = N1,
                 eta = c(0.1, 0.3, 0.1),
                 nu = c(1.1, 1.3, 1.1),
                 cens = 0,
                 beta_L0_D = 0.3,
                 beta_L0_L = 2,
                 beta_L_D = 1,
                 beta_A0_D = -0.1,
                 beta_A0_L = - 2.5)
  
  # Format data for inference
  data <- IntFormatData(data, N_cols = 6)
  
  # Group data based on treatment
  no_treat_group <- data[A0 == 0]
  treat_group <- data[A0 == 1]
  
  # Fit Weibull
  survfit <- survreg(Surv(Time, Delta == 2) ~ 1, 
                     data = no_treat_group[L == 0], 
                     dist='weibull')
    
  # Estimates in no treatment group
  nu_est <- 1/survfit$scale
  eta_est <- 1/(exp(survfit$coefficients[1]))^nu_est
  
  # Generate large data set under the intervened intensity 
  data_new <- simT2D(N = N2, 
                   eta = c(0.1, 0.3, eta_est),
                   nu = c(1.1, 1.3, nu_est),
                   cens = 0,
                   beta_L0_D = 0.3,
                   beta_L0_L = 0,
                   beta_L_D = 1,
                   beta_A0_D = -0.1,
                   beta_A0_L = 0)
  
  # Generate large data set without intervened intensity
  data_new_no_int <- simT2D(N = N2,
                          eta = c(0.1, 0.3, 0.1),
                          nu = c(1.1, 1.3, 1.1),
                          cens = 0,
                          beta_L0_D = 0.3,
                          beta_L0_L = 2,
                          beta_L_D = 1,
                          beta_A0_D = -0.1,
                          beta_A0_L = - 2.5)
  
  #Proportion of subjects dying before some time $\tau$ in treatment group
  MC_ests_T2D[b,] <- c(mean(data_new_no_int[Delta == 1 & A0 == 1, Time] < tau),  # without intervention
                       mean(data_new[Delta == 1 & A0 == 1, Time] < tau))         # with intervention
}
```

```{r}
beta_true <- mean(MC_ests_T2D[,1]-MC_ests_T2D[,2])
beta_true
var(MC_ests_T2D[,1]-MC_ests_T2D[,2])
```


# Intervention effect estimation

Gentagne estimationer:

```{r}
set.seed(735)
B <- 600
tau <- 2
N1 <- 1000
N2 <- 10^5

# For results
simres_t2d <- matrix(nrow = B, ncol = 2)

# Defining intervention
int_a0_0 <- function(j, data) {
  if(j == 2) data$A0 <- 0 
  return(data)
}

for(b in 1:B){
  print(b)
  # Generate "observed" data
  data <- simT2D(N = N1,
                 eta = c(0.1, 0.3, 0.1),
                 nu = c(1.1, 1.3, 1.1),
                 cens = 1,
                 beta_L0_D = 0.3,
                 beta_L0_L = 2,
                 beta_L_D = 1,
                 beta_A0_D = -0.1,
                 beta_A0_L = - 2.5)
    
  # Estimate
  data <- IntFormatData(data, N_cols = 6)
  cox_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A0 + L, data = data)
  cox_t2d <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0, data = data[L == 0])
  cox_fits <- list("D" = cox_death, "L" = cox_t2d)
  
  # Simulate under intervention
  data_int <- simEventCox(N2, cox_fits, L0_old = data$L0, A0_old = data$A0, intervention = int_a0_0)
  
  # Simulate under "observed" intensities
  data0 <- simEventCox(N2, cox_fits, L0_old = data$L0, A0_old = data$A0)
  
  # Calculate estimate and save
  simres_t2d[b,] <- c(mean(data0[Delta == 1 & A0 == 1, Time] < tau), 
                      mean(data_int[Delta == 1 & A0 == 1, Time] < tau))
}
```

```{r}
mean(simres_t2d[,1]-simres_t2d[,2])
sd(simres_t2d[,1]-simres_t2d[,2])
quantile(simres_t2d[,1]-simres_t2d[,2], 0.025)
quantile(simres_t2d[,1]-simres_t2d[,2], 0.975)

pp<- ggplot()+
  geom_histogram(aes(x = simres_t2d[,1]-simres_t2d[,2], y = ..density..), color = "white", fill = "steelblue")+
  geom_vline(xintercept = beta_true, color = "darkred")+
  xlab("Estimate") 

ggsave("hist_sim_int_t2d.jpeg", pp, width = 7, height = 5)
```





