---
title: "Estimations"
author: "Michaela Lukacova"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
# Libraries
library(data.table)
library(survival)
library(simevent)
library(ggplot2)
library(prodlim)
library(rstpm2)
theme_set(theme_bw())
```

# T2D

## Generate data

```{r}
set.seed(373)
data <- simT2D(N = 5000, beta_L0_L = 1, beta_L0_D = 1, beta_L_D = 0.5, beta_A0_L = 1)
```

## Estimation

We fit the models

```{r}
# Transform data into tstart tstop format
data_int <- IntFormatData(data, N_cols = 6)

# Fit Cox models
cox_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A0 + L, data = data_int)
cox_t2d <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0, data = data_int[L == 0])
```

```{r}
predict_data <- data.frame("L0" = c(0.5,0.5), "A0" = c(1, 1), "L" = c(0,1))

basehazz_t2d <- basehaz(cox_t2d, centered = TRUE)
basehazz_death <- basehaz(cox_death, centered = TRUE)
cox_term_t2d <- exp(predict(cox_t2d, newdata=predict_data, type="lp"))
cox_term_death <- exp(predict(cox_death, newdata=predict_data, type="lp"))
cum_int_t2d <- outer(basehazz_t2d[['hazard']], cox_term_t2d, "*")
cum_int_death <- outer(basehazz_death[['hazard']], cox_term_death, "*")

true_surv_death_func1 <- function(t) exp( - 0.1  * t^(1.1) * exp(sum(predict_data[1,] * c(1,0,0.5))))
true_surv_death_func2 <- function(t) exp( - 0.1  * t^(1.1) * exp(sum(predict_data[2,] * c(1,0,0.5))))
true_surv_t2d_func <- function(t) exp( - 0.1  * t^(1.1)  * exp(sum(predict_data[1,] * c(1,1,0))))
```


## Simulate new data

```{r}
cox_fits <- list("D" = cox_death, "L" = cox_t2d)
new_data <- simEventCox(2000, cox_fits, L0_old = data$L0, A0_old = data$A0)
```


## check whether simulated data has the desired intensitities...

```{r}
# Transform data into tstart tstop format
data_int2 <- IntFormatData(new_data, N_cols = 6:7)

# Fit Cox models
cox_death2 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A0 + L, data = data_int2)
cox_t2d2 <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0, data = data_int2[L == 0])
basehazz_t2d2 <- basehaz(cox_t2d2, centered = FALSE)
basehazz_death2 <- basehaz(cox_death2, centered = FALSE)

cox_term_t2d2 <- exp(predict(cox_t2d2, newdata=predict_data, type="lp", reference = "zero"))
cox_term_death2 <- exp(predict(cox_death2, newdata=predict_data, type="lp", reference = "zero"))
cum_int_t2d2 <- outer(basehazz_t2d2[['hazard']], cox_term_t2d2, "*")
cum_int_death2 <- outer(basehazz_death2[['hazard']], cox_term_death2, "*")

gridExtra::grid.arrange(
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death[,1])), color = "red") +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2[,1])), color = "blue") + 
    geom_function(fun = true_surv_death_func1),
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death[,2])), color = "red") +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2[,2])), color = "blue") + 
    geom_function(fun = true_surv_death_func2),
  ggplot()+
    geom_line(aes(x = basehazz_t2d$time, y = exp(-cum_int_t2d[,1])), color = "red") +
    geom_line(aes(x = basehazz_t2d2$time, y = exp(-cum_int_t2d2[,1])), color = "blue") + 
    geom_function(fun = true_surv_t2d_func),
  ggplot()+
    geom_line(aes(x = basehazz_t2d$time, y = exp(-cum_int_t2d[,2])), color = "red") +
    geom_line(aes(x = basehazz_t2d2$time, y = exp(-cum_int_t2d2[,2])), color = "blue") + 
    geom_function(fun = true_surv_t2d_func),
  nrow = 2)
```

## Simulate data under intervention

```{r}
int_a0_0 <- function(j, data) {
  if(j == 2) data$A0 <- 0 
  return(data)
}
new_data <- simEventCox(3000, cox_fits, L0_old = data$L0, A0_old = data$A0, intervention = int_a0_0)

# Transform data into tstart tstop format
data_int3 <- IntFormatData(new_data, N_cols = 6:7)

# Fit Cox models
cox_death3 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A0 + L, data = data_int3)
cox_t2d3 <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + A0, data = data_int3[L == 0])
basehazz_t2d3 <- basehaz(cox_t2d3, centered = TRUE)
basehazz_death3 <- basehaz(cox_death3, centered = TRUE)

cox_term_t2d3 <- exp(predict(cox_t2d3, newdata=predict_data, type="lp"))
cox_term_death3 <- exp(predict(cox_death3, newdata=predict_data, type="lp"))
cum_int_t2d3 <- outer(basehazz_t2d3[['hazard']], cox_term_t2d3, "*")
cum_int_death3 <- outer(basehazz_death3[['hazard']], cox_term_death3, "*")

gridExtra::grid.arrange(
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death[,1])), color = "red", linetype = 2) +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2[,1])), color = "blue", linetype = 2) + 
    geom_line(aes(x = basehazz_death3$time, y = exp(-cum_int_death3[,1])), color = "green", linetype = 2) + 
    geom_function(fun = true_surv_death_func1),
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death[,2])), color = "red", linetype = 2) +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2[,2])), color = "blue", linetype = 2) +
    geom_line(aes(x = basehazz_death3$time, y = exp(-cum_int_death3[,2])), color = "green", linetype = 2) + 
    geom_function(fun = true_surv_death_func2),
  ggplot()+
    geom_line(aes(x = basehazz_t2d$time, y = exp(-cum_int_t2d[,1])), color = "red", linetype = 2) +
    geom_line(aes(x = basehazz_t2d2$time, y = exp(-cum_int_t2d2[,1])), color = "blue", linetype = 2) + 
    geom_line(aes(x = basehazz_t2d3$time, y = exp(-cum_int_t2d3[,1])), color = "green", linetype = 2) + 
    geom_function(fun = true_surv_t2d_func),
  ggplot()+
    geom_line(aes(x = basehazz_t2d$time, y = exp(-cum_int_t2d[,2])), color = "red", linetype = 2) +
    geom_line(aes(x = basehazz_t2d2$time, y = exp(-cum_int_t2d2[,2])), color = "blue", linetype = 2) + 
    geom_line(aes(x = basehazz_t2d3$time, y = exp(-cum_int_t2d3[,2])), color = "green", linetype = 2) + 
    geom_function(fun = true_surv_t2d_func),
  nrow = 2)
```

# Confounder

## Generate data

```{r}
set.seed(373)
data <- simConfounding(N = 20000)   
```

## Estimation

We fit the models

```{r}
# Transform data into tstart tstop format
data_int <- IntFormatData(data, N_cols = 5:6)

# Fit Cox models
cox_death <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A + L, data = data_int)
cox_treat <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + L, data = data_int[A == 0])
cox_conf <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A, data = data_int[L == 0])
```


```{r}
predict_data <- data.frame("L0" = 0.5, "A" = 1, "L" = 0)

basehazz_death <- basehaz(cox_death, centered = FALSE)
basehazz_treat <- basehaz(cox_treat, centered = FALSE)
basehazz_conf <- basehaz(cox_conf, centered = FALSE)
cum_int_death <- basehazz_death[['hazard']] *  exp(predict(cox_death, newdata=predict_data, type="lp"))
cum_int_treat <- basehazz_treat[['hazard']] * exp(predict(cox_treat, newdata=predict_data, type="lp"))
cum_int_conf <- basehazz_conf[['hazard']] *  exp(predict(cox_conf, newdata=predict_data, type="lp")) 

true_surv_death_func1 <- function(t) exp( - 0.1  * t^(1.1) * exp(sum(predict_data * c(1,-1,1))))
true_surv_treat_func1 <- function(t) exp( - 0.1  * t^(1.1) * exp(sum(predict_data * c(1,0,1))))
true_surv_conf_func1 <- function(t) exp( - 0.1  * t^(1.1) * exp(sum(predict_data * c(1, -0.5,0))))

gridExtra::grid.arrange(
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death)), color = "red") +
    geom_function(fun = true_surv_death_func1),
  ggplot()+
    geom_line(aes(x = basehazz_treat$time, y = exp(-cum_int_treat)), color = "red") +
    geom_function(fun = true_surv_treat_func1),
  ggplot()+
    geom_line(aes(x = basehazz_conf$time, y = exp(-cum_int_conf)), color = "red") +
    geom_function(fun = true_surv_conf_func1),
  nrow = 2)
```

## Simulate new data

```{r}
cox_fits <- list("D" = cox_death, "A" = cox_treat, "L" = cox_conf)
new_data <- simEventCox(5000, 
                        cox_fits, 
                        L0_old = data$L0, 
                        A0_old = 0,
                        n_event_max = c(1,1,1))
new_data[,A0:= NULL]
```


## check whether simulated data has the desired intensitities...

```{r}
# Transform data into tstart tstop format
data_int2 <- IntFormatData(new_data, N_cols = 5:7)

# Fit Cox models
cox_death2 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + A + L, data = data_int2)
cox_treat2 <- coxph(Surv(tstart, tstop, Delta == 2) ~ L0 + L, data = data_int2[A == 0])
cox_conf2 <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0 + A, data = data_int2[L == 0])
basehazz_death2 <- basehaz(cox_death2, centered = FALSE)
basehazz_treat2 <- basehaz(cox_treat2, centered = FALSE)
basehazz_conf2 <- basehaz(cox_conf2, centered = FALSE)

cum_int_death2 <- basehazz_death2[['hazard']] * exp(predict(cox_death2, newdata=predict_data, type="lp"))
cum_int_treat2 <- basehazz_treat2[['hazard']]* exp(predict(cox_treat2, newdata=predict_data, type="lp"))
cum_int_conf2 <- basehazz_conf2[['hazard']] * exp(predict(cox_conf2, newdata=predict_data, type="lp"))

gridExtra::grid.arrange(
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death)), color = "red") +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2)), color = "blue") + 
    geom_function(fun = true_surv_death_func1),
  ggplot()+
    geom_line(aes(x = basehazz_treat$time, y = exp(-cum_int_treat)), color = "red") +
    geom_line(aes(x = basehazz_treat2$time, y = exp(-cum_int_treat2)), color = "blue") + 
    geom_function(fun = true_surv_treat_func1),
  ggplot()+
    geom_line(aes(x = basehazz_conf$time, y = exp(-cum_int_conf)), color = "red") +
    geom_line(aes(x = basehazz_conf2$time, y = exp(-cum_int_conf2)), color = "blue") + 
    geom_function(fun = true_surv_conf_func1),
  nrow = 2)
```

## Simulate data under intervention

```{r}
new_data <- simEventCox(3000, 
                        cox_fits, 
                        L0_old = data$L0, 
                        A0_old = 0,
                        n_event_max = c(1,0,1))

# Transform data into tstart tstop format
data_int2 <- IntFormatData(new_data, N_cols = 6:8)

# Fit Cox models
cox_death2 <- coxph(Surv(tstart, tstop, Delta == 1) ~ L0 + L, data = data_int2)
cox_conf2 <- coxph(Surv(tstart, tstop, Delta == 3) ~ L0, data = data_int2[L == 0])
basehazz_death2 <- basehaz(cox_death2, centered = FALSE)
basehazz_conf2 <- basehaz(cox_conf2, centered = FALSE)

cum_int_death2 <- basehazz_death2[['hazard']] * exp(predict(cox_treat2, newdata=predict_data, type="lp"))
cum_int_conf2 <- basehazz_conf2[['hazard']] * exp(predict(cox_conf2, newdata=predict_data, type="lp"))

gridExtra::grid.arrange(
  ggplot()+
    geom_line(aes(x = basehazz_death$time, y = exp(-cum_int_death)), color = "red") +
    geom_line(aes(x = basehazz_death2$time, y = exp(-cum_int_death2)), color = "blue") + 
    geom_function(fun = true_surv_death_func1),
  ggplot()+
    geom_line(aes(x = basehazz_treat$time, y = exp(-cum_int_treat)), color = "red") +
    #geom_line(aes(x = basehazz_treat2$time, y = exp(-cum_int_treat2[,1])), color = "blue") + 
    geom_function(fun = true_surv_treat_func1),
  ggplot()+
    geom_line(aes(x = basehazz_conf$time, y = exp(-cum_int_conf)), color = "red") +
    geom_line(aes(x = basehazz_conf2$time, y = exp(-cum_int_conf2)), color = "blue") + 
    geom_function(fun = true_surv_conf_func1),
  nrow = 2)
```

